name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - name: Install GUI
        run: | 
          sudo apt-get install libxkbcommon-x11-0

#      - name: Install GUI
#        run: | 
#          sudo apt-get install xorg
#          sudo apt-get install --no-install-recommends ubuntu-desktop
#          sudo apt-get install xcb
#          sudo apt-get install libxcb-xinerama0

      - name: Download app and script
        run: |
          cd ~
          ls -l
          curl -O -L https://github.com/AndrewSazonov/ubuntu_screen_record/releases/download/v0.1/SilentInstall.js
          curl -O -L https://github.com/AndrewSazonov/ubuntu_screen_record/releases/download/v0.1/easyDiffraction_Linux_x86-64_v0.0.5_ubuntu-18.04.zip
          unzip easyDiffraction_Linux_x86-64_v0.0.5_ubuntu-18.04.zip

#      - name: Install app
#        run: |
#          sudo startx ~/easyDiffraction_Linux_x86-64_v0.0.5 --verbose --script ~/SilentInstall.js
#
#      - name: Run app
#        run: |
#          sudo startx /root/easyDiffraction/easyDiffraction/easyDiffraction test


#      - name: Install app
#        run: |
#          Xvfb :99 &
#          export DISPLAY=:99
#          /home/runner/easyDiffraction_Linux_x86-64_v0.0.5 --verbose --script ~/SilentInstall.js
#      - name: Run app
#        run: |
#          Xvfb :99 &
#          export DISPLAY=:99
#          /home/runner/easyDiffraction/easyDiffraction/easyDiffraction test
          

      - name: Install app
        run: |
          ls -l /home/runner
          xvfb-run -a ~/easyDiffraction_Linux_x86-64_v0.0.5 --verbose --script ~/SilentInstall.js
      - name: Run app
        run: |
          ls -l /home/runner
          xvfb-run -a /home/runner/easyDiffraction/easyDiffraction/easyDiffraction test


 #     - name: Install app
 #       run: |
 #         export DISPLAY=':99.0'
 #         Xvfb :99 -screen 0 1440x1080x24 > /dev/null 2>&1 &
 #         /home/runner/easyDiffraction_Linux_x86-64_v0.0.5 --verbose --script ~/SilentInstall.js
 #     - name: Run app
 #       run: |
 #         export DISPLAY=':99.0'
 #         Xvfb :99 -screen 0 1440x1080x24 > /dev/null 2>&1 &
 #         /home/runner/easyDiffraction/easyDiffraction/easyDiffraction test


      - name: List dir content
        run: |
          ls -l /home/runner
