name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      - name: Install GUI
        run: | 
          sudo apt-get install libxkbcommon-x11-0

      - name: Download app and script
        run: |
          cd ~
          ls -l
          curl -O -L https://github.com/AndrewSazonov/ubuntu_screen_record/releases/download/v0.1/SilentInstall.js
          curl -O -L https://github.com/AndrewSazonov/ubuntu_screen_record/releases/download/v0.1/easyDiffraction_Linux_x86-64_v0.0.5_ubuntu-18.04.zip
          unzip easyDiffraction_Linux_x86-64_v0.0.5_ubuntu-18.04.zip

#      - name: Install app
#        run: |
#          ls -l /home/runner
#          xvfb-run --server-args "-screen 0 1440x1080x24" /home/runner/easyDiffraction_Linux_x86-64_v0.0.5 --verbose --script /home/runner/SilentInstall.js
#          
#      - name: Run app
#        run: |
#          ls -l /home/runner
#          xvfb-run --server-args "-screen 0 1440x1080x24" /home/runner/easyDiffraction/easyDiffraction/easyDiffraction test

      - name: Set up Xvfb
        run: |
          Xvfb :0 -screen 0 1440x1080x24 -ac &
          export DISPLAY=:0

      - name: Install app
        run: |
          /home/runner/easyDiffraction_Linux_x86-64_v0.0.5 --verbose --script /home/runner/SilentInstall.js

      - name: Run app
        run: |
          /home/runner/easyDiffraction/easyDiffraction/easyDiffraction test

      - name: List dir content
        run: |
          ls -l ~
          ls -l /home/runner
          ls -l /home/runner/easyDiffraction
          ls -l /home/runner/easyDiffraction/easyDiffraction
