name: build Linux

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Download app and script
        run: |
          curl -O -L https://github.com/AndrewSazonov/ubuntu_screen_record/releases/download/v0.2/SilentInstall.js
          curl -O -L https://github.com/AndrewSazonov/ubuntu_screen_record/releases/download/v0.2/easyDiffraction_Windows_x86-32_v0.0.5_DAS-282.zip
          unzip easyDiffraction_Windows_x86-32_v0.0.5.zip
      
      - name: Install app
        run: easyDiffraction_Windows_x86-32_v0.0.5_DAS-282.exe --verbose --script SilentInstall.js

      - name: Run app
        run: C:\easyDiffraction --testmode

