name: build Linux

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
        
        
      - name: Vmware 1
        if: runner.os == '.Windows'
        run: |
          & "C:\Program Files\VMware\VMware Tools\VMwareResolutionSet.exe" 0 1 , 0 0 1440 900
          Get-DisplayResolution

      - name: Vmware 2
        if: runner.os == '.Windows'
        run: |
          "C:\Program Files (x86)\VMware\VMware Tools\VMwareResolutionSet.exe" 0 1 , 0 0 1440 900
        

      - name: AAA
        if: runner.os == '.Windows'
        run: |
          Get-ChildItem -Path C:\ -Filter VWwareResolutionSet.exe -File -Recurse -ErrorAction SilentlyContinue -Force
        #  ls C:\
        #  ls C:\Users
        #  ls 'C:\Program Files'
        #  ls 'C:\Program Files (x86)'
          
      - name: Set up screen recording dependencies (Windows)
        if: runner.os == '.Windows'
        run: |
          Get-DisplayResolution
          Set-DisplayResolution -Width 1920 -Height 1080 -Force
          Get-DisplayResolution              

        
      - name: Set up screen recording dependencies (Windows)
        if: runner.os == '.Windows'
        run: |
          Get-DisplayResolution
          Set-DisplayResolution -Width 1440 -Height 1080 -Force
          Get-DisplayResolution
          curl -O -L https://github.com/AndrewSazonov/ubuntu_screen_record/releases/download/v0.2/QRes.zip
          unzip QRes.zip
          .\QRes.exe /x:1440 /y:1080

      - name: Download app and script
        if: runner.os == '.Windows'
        run: |
          curl -O -L https://github.com/AndrewSazonov/ubuntu_screen_record/releases/download/v0.2/SilentInstall.js
          curl -O -L https://github.com/AndrewSazonov/ubuntu_screen_record/releases/download/v0.2/easyDiffraction_Windows_x86-32_v0.0.5_DAS-282.zip
          unzip easyDiffraction_Windows_x86-32_v0.0.5_DAS-282.zip
      
      - name: Install app
        if: runner.os == '.Windows'
        run: .\easyDiffraction_Windows_x86-32_v0.0.5.exe --verbose --script SilentInstall.js

      - name: Run app
        if: runner.os == '.Windows'
        run: C:\easyDiffraction\easyDiffraction\easyDiffraction.exe --testmode

